default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: block_editor_sample_development

test:
  <<: *default
  database: block_editor_sample_test

production:
  <<: *default
  database: block_editor_sample_production
  username: block_editor_sample
  password: <%= ENV['BLOCK_EDITOR_SAMPLE_DATABASE_PASSWORD'] %>

